name: Go Build, Lint, and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go mod download

      - name: Lint code
        run: go fmt ./... && go vet ./...

      - name: Run tests
        run: go test -v ./...
